meta_product_name: "Nowmada"
meta_title: "Portal de empleo remoto y recursos en español | Nowmada"
meta_description: "Nowmada es la primera bolsa de empleo remoto en español. Encuentra las últimas ofertas de trabajo remoto y empieza tu camino como nómada digital. Si eres una empresa,  no te límites a una búsqueda local, encuentra el mejor talento entre millones de hispano hablantes. El futuro no tiene fronteras y tu empresa tampoco, emplea en remoto!"
meta_image: "bg3.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@esnowmada"              # indispensable pour les Twitter Cards
